name: Terraform Apply 

on: 
  workflow_dispatch: 

jobs: 
  apply: 
    runs-on: ubuntu-latest

    steps: 
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Terraform Configuration
      uses: hashicorp/setup-terraform@v3

    - name: AWS Configuration
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform init
      working-directory: terraform 
      run: terraform init -input=false -no-color

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with: 
        name: tfplan
        path: terraform/tfplan #where it will be donwloaded

    - name: Terraform Apply
      working-directory: terraform 
      run: terraform apply --auto-approve terraform/tfplan
        



    


