name: Build and Push Docker Image To ECR

on:
  push: 
    branches: 
      - master
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:  
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          

      - name: AWS ECR log-in
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t threatimage ./app

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: threatimage:latest
          format: table
          exit-code: 1        
          ignore-unfixed: true
          severity: CRITICAL

      - name: Tag and Push to ECR
        run: |
          Image_URI=${{ secrets.ECR_URI }}
          docker tag threatimage $Image_URI:latest
          docker push $Image_URI:latest

    
