name: Terraform CI/CD

on: 
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual run

jobs:
  plan-job:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v3

      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false -no-color

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan -input=false -no-color

      - name: Save Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  apply-job:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan-job           # <-- waits for plan-job to finish
    environment: production   # optional: enables manual approval in GitHub UI
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v3

      - name: AWS Configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false -no-color

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform  # downloads as terraform/tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve tfplan
