name: Terraform apply 


on: 
  push: 
    branches: 
      - main
# on: 
#   workflow_run: 
#     workflows: ["Build and Push Docker Image To ECR"]
#     types: 
#       - completed
#     branches: 
#       - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: AWS Config
        uses: aws-actions/configure-aws-credentials@v4
        with:  
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform 
        run: terraform init 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Bootstrap Plan
        run: |
          cd terraform-bootstrap
          terraform init
          terraform plan

      - name: Terraform Main Plan
        run: |
          cd ../terraform 
          terraform init
          echo "about to create a terraform plan"
          terraform plan 

      # - name: Terraform Plan (save to file and show)
      #   run: |
      #     terraform plan -out=tfplan
      #     terraform show -no-color tfplan

      # - name: Upload Plan Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: tfplan
      #     path: tfplan








#code checkout
#terraform setup
#aws config
#terraform init
#terraform validate
#terraform plan 
#terraform 





    